/* SCR-021 / Daily Sales / Default */
import AdminTopHeader from "../../components/admin/AdminTopHeader.jsx";

function PaymentShareRows() { return <><div className="sales-share-card__row"><p><span>카드</span><b>67%</b></p><i><em className="is-primary" style={{ width: "67%" }} /></i></div><div className="sales-share-card__row"><p><span>카카오페이</span><b>33%</b></p><i><em style={{ width: "33%" }} /></i></div><div className="sales-share-card__row"><p><span>현금</span><b>0%</b></p><i><em style={{ width: "0%" }} /></i></div></>; }
function OrderShareRows() { return <><div className="sales-share-card__row"><p><span>매장</span><b>33%</b></p><i><em className="is-primary" style={{ width: "33%" }} /></i></div><div className="sales-share-card__row"><p><span>포장</span><b>67%</b></p><i><em style={{ width: "67%" }} /></i></div><div className="sales-share-card__row"><p><span>배달</span><b>0%</b></p><i><em style={{ width: "0%" }} /></i></div></>; }

export default function DailySalesPage() {
  return <section className="sales-daily" data-figma-node="134:11150">
    <AdminTopHeader crumb="Admin / 일별 매출" title="일별 매출" description="일자별 매출 현황 및 시간대 분석"><div className="sales-daily__date"><button type="button" disabled aria-label="이전 날짜">‹</button><span>2026.07.10 (금)</span><button type="button" disabled aria-label="다음 날짜">›</button></div></AdminTopHeader>
    <div className="sales-daily__kpis"><article><span>총매출</span><strong>392,500원</strong><p><b>↓ 18.5%</b><small>전일 대비</small></p></article><article><span>주문 수</span><strong>36건</strong><p><b>↓ 14.3%</b><small>전일 대비</small></p></article><article><span>평균 객단가</span><strong>10,903원</strong><p><b>↓ 4.9%</b><small>전일 대비</small></p></article><article><span>피크 시간대</span><strong>12:00~13:00</strong><p className="is-peak"><b>128,000원</b></p></article></div>
    <div className="sales-daily__middle"><section className="sales-chart"><h2>시간대별 매출</h2><div className="sales-chart__body"><div className="sales-chart__bars"><i style={{ height: "40px" }} /><i style={{ height: "30px" }} /><i style={{ height: "45px" }} /><i className="is-peak" style={{ height: "60px" }} /><i style={{ height: "50px" }} /><i style={{ height: "35px" }} /><i style={{ height: "25px" }} /><i style={{ height: "20px" }} /><i style={{ height: "15px" }} /><i style={{ height: "10px" }} /><i style={{ height: "5px" }} /><i style={{ height: "5px" }} /></div><div className="sales-chart__ticks"><span>10시</span><span>12시</span><span>14시</span><span>16시</span><span>18시</span><span>20시</span><span>21시</span></div></div><p className="sales-chart__peak"><b>128,000원</b><span>피크 시간 12:00</span></p></section>
    <div className="sales-daily__right"><section className="sales-share-card"><h2>결제수단별 매출</h2><div className="sales-share-card__rows"><PaymentShareRows /></div></section><section className="sales-share-card"><h2>주문 유형별 매출</h2><div className="sales-share-card__rows"><OrderShareRows /></div></section><section className="sales-ranking"><h2>메뉴별 판매 순위</h2><div className="sales-ranking__rows"><div className="sales-ranking__row"><span className="sales-ranking__rank">1</span><span className="sales-ranking__name">탄단지 샐러디</span><span className="sales-ranking__count">11건</span><b className="sales-ranking__amount">97,900원</b></div><div className="sales-ranking__row"><span className="sales-ranking__rank">2</span><span className="sales-ranking__name">우삼겹 포케볼</span><span className="sales-ranking__count">8건</span><b className="sales-ranking__amount">87,200원</b></div><div className="sales-ranking__row"><span className="sales-ranking__rank">3</span><span className="sales-ranking__name">시저치킨 랩</span><span className="sales-ranking__count">7건</span><b className="sales-ranking__amount">53,200원</b></div><div className="sales-ranking__row"><span className="sales-ranking__rank">4</span><span className="sales-ranking__name">우삼겹 메밀면 누들볼</span><span className="sales-ranking__count">5건</span><b className="sales-ranking__amount">49,500원</b></div><div className="sales-ranking__row"><span className="sales-ranking__rank">5</span><span className="sales-ranking__name">—</span><span className="sales-ranking__count">—</span><b className="sales-ranking__amount">—</b></div></div></section></div></div>
    <section className="sales-table"><h2>시간대별 상세</h2><div className="sales-table__grid sales-table__grid--hourly"><div className="sales-table__head"><span>시간대</span><span>주문 수</span><span>매출</span><span>객단가</span></div><div className="sales-table__row"><span>10:00-11:00</span><span>4</span><span>42,000원</span><span>10,500원</span></div><div className="sales-table__row"><span>11:00-12:00</span><span>6</span><span>68,400원</span><span>11,400원</span></div><div className="sales-table__row"><span>12:00-13:00</span><span>12</span><span>128,000원</span><span>10,667원</span></div><div className="sales-table__row"><span>13:00-14:00</span><span>8</span><span>87,200원</span><span>10,900원</span></div><div className="sales-table__row"><span>14:00-15:00</span><span>6</span><span>66,900원</span><span>11,150원</span></div></div></section>
  </section>;
}
